// Code generated by errgen; DO NOT EDIT.

package state

import "github.com/trippwill/tuck/internal/apperr"

func (k ErrState) Error() string { return string(k) }

type Error = apperr.Error[ErrState]

func AppErrMsg(sentinel ErrState, msg string) error {
	return apperr.AppErrMsg(sentinel, msg)
}

func AppErrMsgf(sentinel ErrState, format string, args ...any) error {
	return apperr.AppErrMsgf(sentinel, format, args...)
}

func AppErrWrap(sentinel ErrState, err error) error {
	return apperr.AppErrWrap(sentinel, err)
}

func AppErrWrapf(sentinel ErrState, err error, format string, args ...any) error {
	return apperr.AppErrWrapf(sentinel, err, format, args...)
}
