// Code generated by errgen; DO NOT EDIT.

package state

import "github.com/trippwill/tuck/internal/apperr"

func (k ErrState) Error() string { return string(k) }

type StateErr interface {
	error
	comparable
	ErrState
}

type Error[S StateErr] = apperr.Error[S]

func AppErrMsg[S StateErr](sentinel S, msg string) error {
	return apperr.AppErrMsg(sentinel, msg)
}

func AppErrMsgf[S StateErr](sentinel S, format string, args ...any) error {
	return apperr.AppErrMsgf(sentinel, format, args...)
}

func AppErrWrap[S StateErr](sentinel S, err error) error {
	return apperr.AppErrWrap(sentinel, err)
}

func AppErrWrapf[S StateErr](sentinel S, err error, format string, args ...any) error {
	return apperr.AppErrWrapf(sentinel, err, format, args...)
}
