// Code generated by errgen; DO NOT EDIT.

package manifest

import "github.com/trippwill/tuck/internal/apperr"

func (k ErrManifest) Error() string { return string(k) }

type ManifestErr interface {
	error
	comparable
	ErrManifest
}

type Error[S ManifestErr] = apperr.Error[S]

func AppErrMsg[S ManifestErr](sentinel S, msg string) error {
	return apperr.AppErrMsg(sentinel, msg)
}

func AppErrMsgf[S ManifestErr](sentinel S, format string, args ...any) error {
	return apperr.AppErrMsgf(sentinel, format, args...)
}

func AppErrWrap[S ManifestErr](sentinel S, err error) error {
	return apperr.AppErrWrap(sentinel, err)
}

func AppErrWrapf[S ManifestErr](sentinel S, err error, format string, args ...any) error {
	return apperr.AppErrWrapf(sentinel, err, format, args...)
}
