// Code generated by errgen; DO NOT EDIT.

package manifest

import "github.com/trippwill/tuck/internal/apperr"

func (k ErrManifest) Error() string { return string(k) }

type Error = apperr.Error[ErrManifest]

func AppErrMsg(sentinel ErrManifest, msg string) error {
	return apperr.AppErrMsg(sentinel, msg)
}

func AppErrMsgf(sentinel ErrManifest, format string, args ...any) error {
	return apperr.AppErrMsgf(sentinel, format, args...)
}

func AppErrWrap(sentinel ErrManifest, err error) error {
	return apperr.AppErrWrap(sentinel, err)
}

func AppErrWrapf(sentinel ErrManifest, err error, format string, args ...any) error {
	return apperr.AppErrWrapf(sentinel, err, format, args...)
}
