// Code generated by errgen; DO NOT EDIT.

package resolve

import "github.com/trippwill/tuck/internal/apperr"

func (k ErrSource) Error() string { return string(k) }

type Error = apperr.Error[ErrSource]

func AppErrMsg(sentinel ErrSource, msg string) error {
	return apperr.AppErrMsg(sentinel, msg)
}

func AppErrMsgf(sentinel ErrSource, format string, args ...any) error {
	return apperr.AppErrMsgf(sentinel, format, args...)
}

func AppErrWrap(sentinel ErrSource, err error) error {
	return apperr.AppErrWrap(sentinel, err)
}

func AppErrWrapf(sentinel ErrSource, err error, format string, args ...any) error {
	return apperr.AppErrWrapf(sentinel, err, format, args...)
}
