package errgen

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

const apperrImport = "github.com/trippwill/tuck/internal/apperr"

type Options struct {
	TypeName       string
	ConstraintName string
	Dir            string
	Output         string
}

func Generate(options Options) ([]byte, error) {
	typeName, err := normalizeTypeName(options.TypeName)
	if err != nil {
		return nil, err
	}
	if options.ConstraintName != "" {
		return nil, errors.New("-constraint is not supported; errgen uses one sentinel type per package")
	}
	dir := options.Dir
	if dir == "" {
		dir = "."
	}

	info, err := inspectPackage(dir, typeName)
	if err != nil {
		return nil, err
	}

	source, err := render(info.PackageName, typeName)
	if err != nil {
		return nil, err
	}
	if options.Output != "" {
		outputPath := options.Output
		if !filepath.IsAbs(outputPath) {
			outputPath = filepath.Join(dir, outputPath)
		}
		if err := os.WriteFile(outputPath, source, 0o644); err != nil {
			return nil, fmt.Errorf("write output %q: %w", outputPath, err)
		}
	}
	return source, nil
}

type packageInfo struct {
	PackageName string
}

func normalizeTypeName(typeName string) (string, error) {
	typeName = strings.TrimSpace(typeName)
	if typeName == "" {
		return "", errors.New("-type is required")
	}
	if strings.Contains(typeName, ",") {
		return "", errors.New("-type must name exactly one sentinel type")
	}
	return typeName, nil
}

func inspectPackage(dir string, sentinelType string) (packageInfo, error) {
	files, err := parseFiles(dir)
	if err != nil {
		return packageInfo{}, err
	}
	if len(files) == 0 {
		return packageInfo{}, fmt.Errorf("no Go files found in %q", dir)
	}

	packageName := files[0].Name.Name
	typeFound := false
	stringType := false
	constFound := false

	for _, file := range files {
		if file.Name.Name != packageName {
			return packageInfo{}, fmt.Errorf("multiple packages found in %q", dir)
		}

		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}

			switch gen.Tok {
			case token.TYPE:
				for _, spec := range gen.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					declaredType := typeSpec.Name.Name
					if declaredType != sentinelType {
						continue
					}
					typeFound = true
					if ident, ok := typeSpec.Type.(*ast.Ident); ok && ident.Name == "string" {
						stringType = true
					}
				}
			case token.CONST:
				previousType := ""
				for _, spec := range gen.Specs {
					valueSpec, ok := spec.(*ast.ValueSpec)
					if !ok {
						previousType = ""
						continue
					}
					effectiveType := identName(valueSpec.Type)
					if valueSpec.Type == nil {
						if len(valueSpec.Values) == 0 {
							effectiveType = previousType
						} else {
							effectiveType = ""
						}
					}
					if effectiveType == sentinelType {
						constFound = true
					}
					previousType = effectiveType
				}
			}
		}
	}

	if !typeFound {
		return packageInfo{}, fmt.Errorf("type %q not found", sentinelType)
	}
	if !stringType {
		return packageInfo{}, fmt.Errorf("type %q must have underlying type string", sentinelType)
	}
	if !constFound {
		return packageInfo{}, fmt.Errorf("no constants of type %q found", sentinelType)
	}

	return packageInfo{PackageName: packageName}, nil
}

func parseFiles(dir string) ([]*ast.File, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read dir %q: %w", dir, err)
	}

	fset := token.NewFileSet()
	var files []*ast.File
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		path := filepath.Join(dir, name)
		if isGenerated(path) {
			continue
		}
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil, fmt.Errorf("parse %q: %w", path, err)
		}
		files = append(files, file)
	}
	return files, nil
}

func isGenerated(path string) bool {
	contents, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	for _, line := range strings.Split(string(contents), "\n") {
		if strings.Contains(line, "Code generated") && strings.Contains(line, "DO NOT EDIT") {
			return true
		}
		if strings.TrimSpace(line) != "" && !strings.HasPrefix(strings.TrimSpace(line), "//") {
			return false
		}
	}
	return false
}

func identName(expr ast.Expr) string {
	ident, ok := expr.(*ast.Ident)
	if !ok {
		return ""
	}
	return ident.Name
}

func render(packageName string, typeName string) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by errgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", packageName)
	fmt.Fprintf(&b, "import %q\n\n", apperrImport)
	fmt.Fprintf(&b, "func (k %s) Error() string { return string(k) }\n\n", typeName)
	fmt.Fprintf(&b, "type Error = apperr.Error[%s]\n\n", typeName)
	fmt.Fprintf(&b, "func AppErrMsg(sentinel %s, msg string) error {\n", typeName)
	fmt.Fprintf(&b, "\treturn apperr.AppErrMsg(sentinel, msg)\n")
	fmt.Fprintf(&b, "}\n\n")
	fmt.Fprintf(&b, "func AppErrMsgf(sentinel %s, format string, args ...any) error {\n", typeName)
	fmt.Fprintf(&b, "\treturn apperr.AppErrMsgf(sentinel, format, args...)\n")
	fmt.Fprintf(&b, "}\n\n")
	fmt.Fprintf(&b, "func AppErrWrap(sentinel %s, err error) error {\n", typeName)
	fmt.Fprintf(&b, "\treturn apperr.AppErrWrap(sentinel, err)\n")
	fmt.Fprintf(&b, "}\n\n")
	fmt.Fprintf(&b, "func AppErrWrapf(sentinel %s, err error, format string, args ...any) error {\n", typeName)
	fmt.Fprintf(&b, "\treturn apperr.AppErrWrapf(sentinel, err, format, args...)\n")
	fmt.Fprintf(&b, "}\n")

	source, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return source, nil
}
