// Code generated by errgen; DO NOT EDIT.

package plan

import "github.com/trippwill/tuck/internal/apperr"

func (k ErrPlan) Error() string { return string(k) }

type PlanErr interface {
	error
	comparable
	ErrPlan
}

type Error[S PlanErr] = apperr.Error[S]

func AppErrMsg[S PlanErr](sentinel S, msg string) error {
	return apperr.AppErrMsg(sentinel, msg)
}

func AppErrMsgf[S PlanErr](sentinel S, format string, args ...any) error {
	return apperr.AppErrMsgf(sentinel, format, args...)
}

func AppErrWrap[S PlanErr](sentinel S, err error) error {
	return apperr.AppErrWrap(sentinel, err)
}

func AppErrWrapf[S PlanErr](sentinel S, err error, format string, args ...any) error {
	return apperr.AppErrWrapf(sentinel, err, format, args...)
}
