// Code generated by errgen; DO NOT EDIT.

package plan

import "github.com/trippwill/tuck/internal/apperr"

func (k ErrPlan) Error() string { return string(k) }

type Error = apperr.Error[ErrPlan]

func AppErrMsg(sentinel ErrPlan, msg string) error {
	return apperr.AppErrMsg(sentinel, msg)
}

func AppErrMsgf(sentinel ErrPlan, format string, args ...any) error {
	return apperr.AppErrMsgf(sentinel, format, args...)
}

func AppErrWrap(sentinel ErrPlan, err error) error {
	return apperr.AppErrWrap(sentinel, err)
}

func AppErrWrapf(sentinel ErrPlan, err error, format string, args ...any) error {
	return apperr.AppErrWrapf(sentinel, err, format, args...)
}
