// Code generated by errgen; DO NOT EDIT.

package pkgref

import "github.com/trippwill/tuck/internal/apperr"

func (k ErrRef) Error() string { return string(k) }

type Error = apperr.Error[ErrRef]

func AppErrMsg(sentinel ErrRef, msg string) error {
	return apperr.AppErrMsg(sentinel, msg)
}

func AppErrMsgf(sentinel ErrRef, format string, args ...any) error {
	return apperr.AppErrMsgf(sentinel, format, args...)
}

func AppErrWrap(sentinel ErrRef, err error) error {
	return apperr.AppErrWrap(sentinel, err)
}

func AppErrWrapf(sentinel ErrRef, err error, format string, args ...any) error {
	return apperr.AppErrWrapf(sentinel, err, format, args...)
}
