// Code generated by errgen; DO NOT EDIT.

package pkgref

import "github.com/trippwill/tuck/internal/apperr"

func (k ErrRef) Error() string { return string(k) }

type PkgrefErr interface {
	error
	comparable
	ErrRef
}

type Error[S PkgrefErr] = apperr.Error[S]

func AppErrMsg[S PkgrefErr](sentinel S, msg string) error {
	return apperr.AppErrMsg(sentinel, msg)
}

func AppErrMsgf[S PkgrefErr](sentinel S, format string, args ...any) error {
	return apperr.AppErrMsgf(sentinel, format, args...)
}

func AppErrWrap[S PkgrefErr](sentinel S, err error) error {
	return apperr.AppErrWrap(sentinel, err)
}

func AppErrWrapf[S PkgrefErr](sentinel S, err error, format string, args ...any) error {
	return apperr.AppErrWrapf(sentinel, err, format, args...)
}
