// Code generated by errgen; DO NOT EDIT.

package packages

import "github.com/trippwill/tuck/internal/apperr"

func (k ErrPackage) Error() string { return string(k) }

type Error = apperr.Error[ErrPackage]

func AppErrMsg(sentinel ErrPackage, msg string) error {
	return apperr.AppErrMsg(sentinel, msg)
}

func AppErrMsgf(sentinel ErrPackage, format string, args ...any) error {
	return apperr.AppErrMsgf(sentinel, format, args...)
}

func AppErrWrap(sentinel ErrPackage, err error) error {
	return apperr.AppErrWrap(sentinel, err)
}

func AppErrWrapf(sentinel ErrPackage, err error, format string, args ...any) error {
	return apperr.AppErrWrapf(sentinel, err, format, args...)
}
