// Code generated by errgen; DO NOT EDIT.

package packages

import "github.com/trippwill/tuck/internal/apperr"

func (k ErrPackage) Error() string { return string(k) }

type PackagesErr interface {
	error
	comparable
	ErrPackage
}

type Error[S PackagesErr] = apperr.Error[S]

func AppErrMsg[S PackagesErr](sentinel S, msg string) error {
	return apperr.AppErrMsg(sentinel, msg)
}

func AppErrMsgf[S PackagesErr](sentinel S, format string, args ...any) error {
	return apperr.AppErrMsgf(sentinel, format, args...)
}

func AppErrWrap[S PackagesErr](sentinel S, err error) error {
	return apperr.AppErrWrap(sentinel, err)
}

func AppErrWrapf[S PackagesErr](sentinel S, err error, format string, args ...any) error {
	return apperr.AppErrWrapf(sentinel, err, format, args...)
}
